### ISSUE TITLE
Documentation: ADSL Vignette, typo in derive_var_disposition_reason and template script doesn't match sample code

### ISSUE THREAD

**Issue by teckla-gsk** [pharmaverse/admiral#1006]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

The function derive_var_disposition_reason should be derive_VARS_disposition reason. Also, the script within the vignette does not match the example script ad_adsl.R

![image](https://user-images.githubusercontent.com/82049812/157342892-f6ab7c93-885f-458b-8339-cc590828342c.png)

**Comment by rossfarrugia** [comment]
@teckla-gsk i found this has already been fixed by Rena in https://github.com/pharmaverse/admiral/issues/969. Also I don't think the vignettes do always 100% match the templates. The vignettes show more detailed possibilities, but the templates are focused on more the things which are most generic and likely to be needed by all, e.g. vars like DCSREAS are likely quite protocol-specific so the vignette gives an example for if users need to add them. shout if i misunderstand anything though and feel free to re-open this issue.
