### ISSUE TITLE
Documentation:  Search function on the Website does not work

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1040]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Look into the [pkgdown documentation](https://pkgdown.r-lib.org/articles/pkgdown.html) on how to get the Search function working.  Currently does not work.  Reportedly worked a few cycles ago, but had limited search capabilities. 

![image](https://user-images.githubusercontent.com/10111024/159566415-8356248c-d568-43ca-958a-a2e24c780e4e.png)

**Comment by bms63** [comment]
Does not work on Chrome or on Edge.

**Comment by thomas-neitmann** [comment]
Let's switch to native search functionality using okgdown, explained here: https://pkgdown.r-lib.org/articles/search.html

**Comment by PoojaKumari05** [comment]
@thomas-neitmann @bms63 - I think, the reason SEARCH was working before and not working now is because earlier the website url was - "https://roche-gsk.github.io/admiral/news/index.html" and now its updated to "https://pharmaverse.github.io/admiral/index.html". As per the documentation we would need to submit the url to Docsearch and get the api_key, the renaming would not have reflected in Docsearch, and it may consider it as a new website. If this is the case then only the website owner can apply for this request. 
Let me know your thought on this.
![Capture](https://user-images.githubusercontent.com/90273880/164487811-7041d8d6-9ceb-4a1a-a5eb-132450c28914.JPG)

**Comment by bms63** [comment]
Hi @PoojaKumari05 .  If we use the other method do we still need to apply for the request or do anything extra?  I think we want to avoid having to apply for stuff as it makes the issue dependent on the admins, which we want to avoid.  If we can't use the other method, then we can apply.  Let me know if I need to clarify anything.  Thanks!!

**Comment by PoojaKumari05** [comment]
Hi @bms63 @thomas-neitmann - I tried to install the latest "pkgdown" version which has the built-in feature in it, but I am having trouble in getting it installed because of the dependencies. Below is the snapshot of dependent packages. Kindly let me know if I can go ahead and install these 1 by 1 if there wont be any cascading issues upon updating these packages.
![Capture](https://user-images.githubusercontent.com/90273880/165741384-5d13d01d-594e-4a4d-aae5-742a9176326d.JPG)

**Comment by bms63** [comment]
I think you should keep going forward.  It looks like you will need fastmap package installed as well??  I don't think any of these packages are used in the admiral functions.
