### ISSUE TITLE
Feature Request: Implement `derive_extreme_records()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1042]
### Feature Idea

```
derive_extreme_records(
  dataset,
  by_vars,
  order,
  mode,
  filter,
  set_values_to)
```
add the first or last record for each by group as new observations to the input dataset. This is useful for deriving observations for `DTYPE = "MINIMUM"`, `DTYPE = "MAXIMUM"`, or `DTYPE = "LOV"` in BDS datasets.

Function flow:
1. filter input dataset
2. call `filter_extreme()` for the filtered input dataset
3. create/update the variables specified by `set_values_to` in the resulting dataset
4. add the observations from the previous step to the (unfiltered) input dataset

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

```
advs_ex1 <- advs %>%
  derive_var_extreme_flag(
    by_vars = vars(STUDYID, USUBJID, PARAMCD),
    order = vars(ADT, AVISITN, ATPTN, AVAL),
    new_var = EOTFL,
    mode = "last",
    filter = (4 < AVISITN & AVISITN <= 12 & ANL01FL == "Y")
  ) %>%
  filter(EOTFL == "Y") %>%
  mutate(
    AVISIT = "End of Treatment",
    AVISITN = 99
  ) %>%
  union_all(advs) %>%
  select(-EOTFL)
```
from the BDS finding vignette could be simplified to
```
advs_ex1 <- advs %>%
  derive_extreme_records(
    by_vars = vars(STUDYID, USUBJID, PARAMCD),
    order = vars(ADT, AVISITN, ATPTN, AVAL),
    mode = "last",
    filter = (4 < AVISITN & AVISITN <= 12 & ANL01FL == "Y"),
    set_value_to = vars(
      AVISIT = "End of Treatment",
      AVISITN = 99
    )
  )
```

**Comment by bundfussr** [comment]
@rossfarrugia and I discussed this and we think we need the function for deriving `DTYPE` in ADVS (and other BDS finding datasets).

**Comment by rossfarrugia** [comment]
thanks @bundfussr - few more notes to add for whoever picks this one up:
- BDS Finding ADaM vignette should be updated to include one such example, as it would be easy to assume derive_summary_records() is best to use unless you see a prompt
- In the documentation make sure the difference is clear here as well. As Stefan explained to me: I would not try to cover MINIMUM and MAXIMUM by derive_summary_records() because there you populate the by vars only. Source variables like VSSEQ does not make sense for summarized record. For MINIMUM and MAXIMUM you just select a record thus I would keep all variables of the selected record.

**Comment by bundfussr** [comment]
@koegerr , @thomas-neitmann , @bms63 , do you have any objections implementing this function?

**Comment by bms63** [comment]
I cant think of any objections.  @millerg23 @yangc71 Do you think we should implement this in the adlb template script?

**Comment by koegerr** [comment]
Hi,

I am a bit unsure since we basically combining multiple steps into one. Also we pass in whole conditions as arguments if I understand the following example correct:

filter(EOTFL == "Y") %>%
mutate(
    AVISIT = "End of Treatment",
    AVISITN = 99

becomes :

set_value_to = vars(
      AVISIT = "End of Treatment",
      AVISITN = 99)


While it might be simple to have one function I feel we losing more and more the modular approach and step by step functionality. However I also understand that it might be simpler if you really just have to call one function instead of having 2-3 steps. This might be actually an example where combining steps might be better but on the other hand I wonder if it really makes it easier if people want to know what exactly happens while they building their ADaMs.

But fine with me if all others think this is OK.

**Comment by rossfarrugia** [comment]
i see your point Robin but its only for those newly created records you're updating those values and we already do same for https://pharmaverse.github.io/admiral/reference/derive_summary_records.html. for me i think it's quite clear here as the modular step in this case is building the new record, and everything is nicely contained in the one call that does all you need for that new record.

**Comment by thomas-neitmann** [comment]
I'm in favor of implementing this function.
