### ISSUE TITLE
Feature Request:  export `enumerate`, `quo_c`, ...

### ISSUE THREAD

**Issue by amsmith214** [pharmaverse/admiral#1079]
### Feature Idea

Use `enumerate`, `quo_c`, and `extract_vars` explicitly within `{admiralonco}` functions

### Reproducible Example/Pseudo Code

I think this can be accomplished with an `@export` statement in the header to `enumerate`, `quo_c`, and `extract_vars` but may also require unit tests to be developed.

**Comment by bundfussr** [comment]
I wonder if we should export all functions in `dev_utils.R`. Maybe this is easier than exporting them one by one when they are required by an extension package.

@pharmaverse/admiral , what do you think?

**Comment by bms63** [comment]
I think exporting them is fine.  

I think there is unit tests for them already.

Do we want them to prefix them with something so they are easy to find?  For example, dev_quo_c(), dev_enumerate() or some other prefix

**Comment by thomas-neitmann** [comment]
Just an idea: would it be worthwile to have all these development utilities in its own package, e.g. {admiralutils} ot {admiraldev}? I feel that would keep {admiral}itself "cleaner" as it would only contain derivations.

**Comment by bms63** [comment]
Ohh... separate package I like!  Maybe a good one to test the template repo with?

**Comment by rossfarrugia** [comment]
@statasaurus had a similar suggestion previously about the ADaM templates, so I've added a topic on our sponsors/lead meeting tomorrow to discuss "compartmentalising admiral into more dedicated packages".

In the meantime if anyone from @pharmaverse/admiral or @pharmaverse/admiralonco-dev could pick up this issue and implement it in {admiral} for now it would be of great help for our {admiralonco} ongoing development.

**Comment by bundfussr** [comment]
I am not sure if it is worth to put the dev_utils functions into a separate package. It would require some work to setup a new repository and package. It would complicate the development process because if an issue in admiral requires an update of `dev_util.R`, you would need to work on two repositories admiral and admiralutil and use two PRs. Also the release process would be more time-consuming.
 
What is the benefit?

In general I would agree that it could make sense to split admiral into separate packages but I would not do it now. We have just started implementing extension packages. We implemented some admiral functions we need for oncology and I would expect that there will be more. I think the more functions we have the easier it is to split them into reasonable packages. Thus I would wait with this step.

**Comment by bms63** [comment]
> @statasaurus had a similar suggestion previously about the ADaM templates, so I've added a topic on our sponsors/lead meeting tomorrow to discuss "compartmentalising admiral into more dedicated packages".
> 
> In the meantime if anyone from @pharmaverse/admiral or @pharmaverse/admiralonco-dev could pick up this issue and implement it in {admiral} for now it would be of great help for our {admiralonco} ongoing development.

I don't think the tempaltes take up that much room and shouldn't be moved out of admiral.  Makes it easier to keep them in sync with our functions as well.

I'd be more interested in "compartmentalising" the admiral adam datasets as they are too large and starting to really fill up the package.

**Comment by rossfarrugia** [comment]
@bms63 we could move those to a sub-folder in {admiral.test} if people would prefer?
