### ISSUE TITLE
Feature Request:  Add `value_var` parameter to `derive_vars_atc()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1120]
### Feature Idea

Add `value_var` parameter to `derive_vars_atc()`

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

```
derive_vars_atc(
  cm,
  dataset_facm = facm,
  value_var = FAORRES
)
```

**Comment by rossfarrugia** [comment]
@tamarasenior hope you're still ok to pick this one up as discussed as we need it to enable the roche implementation for ADCM

**Comment by rossfarrugia** [comment]
@tamarasenior FYI  we usually leave these open until we make the release just for transparency for our users, or else people may request new issues for things already fixed in `devel`. Also if for future you use "closes #<issue_number>" at the start of your PR title, then github will automaticlaly close these once the changes merge with `main` for the release.
