### ISSUE TITLE
Feature Request: Allow using and listing template from {admiral} extension packages

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1205]
### Feature Idea

We need a way for `list_all_templates()` and `use_ad_template()` to specify in which package to look for the templates. Right now it's restricted to templates that ship with {admiral} itself which is not sufficient going forward as extension packages will contain their own templates.

### Reproducible Example/Pseudo Code

I could think of the following:

```
list_all_templates(package = "admiralxxx")
use_ad_template("adxx", package = "admiralxxx")
```

where `package` is `"admiral"` by default but can be changed to other packages.

**Comment by rossfarrugia** [comment]
i like that idea @thomas-neitmann !

**Comment by thomas-neitmann** [comment]
This suggestion would require people to specify the package in which to look for templates rather than listing all templates across admiral and its extension packages. Does that fit what you had in mind @rossfarrugia?

**Comment by bundfussr** [comment]
Could we have options for
- listing all templates provided by the loaded packages
- listing all templates provided by the installed packages
- listing all templates provided by public admiral packages?

I also wonder if we should add a short description to each template and add the option to list all templates where the description matches a search pattern. I think datasets like ADAE, ADLB, ADSL, are used across all companies but for efficacy and TA specific datasets I would not expect that the same name is used across companies.

**Comment by rossfarrugia** [comment]
Personally I'm ok with keeping this one simple as with Thomas's proposal above, as people would have to know which ext packages they're installing/loading anyway and then they'd check the site (Get Started guide & vignettes) for each which would show what's on offer. It was more the `use_ad_template` i was concerned with rather than the `list_all_templates` which is more of a nice to have as just saves them exploring via the site.

Maybe Stefan's ideas could be implemented more over time though if we hear this feedback from users, but I wouldn't go too complex to start with as we're hoping to have this by end of the month ready for first onco release testing.
