### ISSUE TITLE
Define the scope of release 0.9.0

### ISSUE THREAD

**Issue by duniek** [pharmaverse/admiral#1374]
### Background Information

Create a list of features that would be part of the next release in December.
Highlight which would be the highest priority.

### Definition of Done

List of desired features/ updates available

**Timeline:**  A new release will occur in early December 2022 (release Q4-2022).
**Theme:** Developer and Adoption Focus
**Synopsis:**  

A two prong strategy is adopted.  As admiral sprawls out, we are in need of updating and enhancing our developer documents and processes.  Emphasis will be placed on ensuring that our developer vignettes are up to date with our best practices and that theses are implemented throughout our admiral packages and repos.  At the same time, we also need to ensure that admiral is being adopted at our respective parent companies and the boarder community.  Emphasis will also be placed on updating and creating additional users guides, documentation, video walkthroughs and continuing with our monthly beginner admiral series. 

admiral bugs still receive **the highest priority** to fix and address.  Additional work on new functions, new workflows, etc, with the exception of those identified for this release, should be addressed after we have allocated appropriate resourcing to developer and adoption strategy.  

Issues that address this strategy have been tagged with (release Q4-2022).

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann @millerg23 FYI here's some early ones to add to the list that we'd appreciate consideration to be prioritised for next release from a Roche selfish perspective... 

- https://github.com/pharmaverse/admiral/issues/1338
- https://github.com/pharmaverse/admiral/issues/989 (TRTEMFL) _- i was speaking to Gordon and we were thinking maybe best for @bundfussr to pick this one up as we need to also create an admiralroche version of this later as we have a subtle company-specific addition to the rules here that wouldn't be applicable for admiral_
- https://github.com/pharmaverse/admiral/issues/1337 & https://github.com/pharmaverse/admiral/issues/1336 (@tamarasenior already assigned to)
- https://github.com/pharmaverse/admiral/issues/1041
- using {parttime} as a dependency for the datetime parsing if it's ready in time: https://github.com/pharmaverse/admiral/issues/1315
- bring admiraltemplate in line with admiral latest conventions: https://github.com/pharmaverse/admiraltemplate/issues/37
- all the pieces discussed with @cicdguy around using admiralci directly for the workflows and enabling multi-version docs so that anyone can view the latest site from `devel` anytime without all the links breaking

**Comment by bms63** [comment]
* Creating another demo video for the youtube channel should be added
* Merger Vignette #734 
* Bring boards together from admiral.test, admiraci, admiraldev and admiral core

**Comment by bms63** [comment]
#1235 Address 2 issues created around `library(pkg_name)` and `pkg_name::function()`

**Comment by rossfarrugia** [comment]
and https://github.com/pharmaverse/admiral/issues/1295 on similar note

**Comment by duniek** [comment]
Note from our meeting:
general theme: development focus
some issues are needed for admiralRoche
issues needed for ADLB
admiral dev code coverage boost up to 80%
admiral.dev
PK - potentially a separate extension package

push on adoption side - event/hackathon across industry
additional videos: admiral intro, how to build additional datasets

**Comment by esimms999-gsk** [comment]
Have a discussion wrt translating documentation to other languages. If this is something we eventually want done, then attempt to translate one portion of the documentation (ReadMe?) from English to another language and figure out how that and subsequent translations can be managed.

**Comment by cicdguy** [comment]
> Have a discussion wrt translating documentation to other languages. If this is something we eventually want done, then attempt to translate one portion of the documentation (ReadMe?) from English to another language and figure out how that and subsequent translations can be managed. 

Does Google Translate help here? One can easily embed translation features into the pkgdown docs.

**Comment by rossfarrugia** [comment]
> Have a discussion wrt translating documentation to other languages. If this is something we eventually want done, then attempt to translate one portion of the documentation (ReadMe?) from English to another language and figure out how that and subsequent translations can be managed.

Maybe one more for down the line? I'd personally still say we have plenty of common template/function gaps I'd prefer us cover above this like hy's law, questionnaires, what to do with crossover/periods, etc.

**Comment by bundfussr** [comment]
I tried to translate the admiral page to German with google translate. Most of the text is readable but I would prefer reading the original version. (Some parts are funny but not helpful, e.g., google tries to translate the argument names on the function documentation pages.)

I agree with @rossfarrugia that there are more important topics. I think the main question is if we have resources to work on them.

**Comment by rossfarrugia** [comment]
> I think the main question is if we have resources to work on them.

Still working on new resources... trying to bring 2.5 more devs our way over next month or 2 🤞

**Comment by thomas-neitmann** [comment]
As for resources, there are apparently 5 new hires out of SSF that are keen to contribute to our next gen tools. I'd like to get them involved with writing unit tests for {admiraldev} first. Once they get the hang of our process I'm sure they'd be eager to contribute to issues within {admiral}. I'll keep ypu posted on updates.
