### ISSUE TITLE
Documentation:  Update tests on using library(pkg_name) versus pkg_name::function

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#1381]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

See #1235 for additional discussion and guidance.

**Comment by thomas-neitmann** [comment]
@esimms999-gsk Please go ahead and take this on.

**Comment by esimms999-gsk** [comment]
I spoke with Ellis Hughes at GSK about this. His take on it:

_In your package code, you should be using the importFrom tags for your functions to identify 
which functions from your various libraries to make available internally. However, the functions 
needed for testing may not be the same as you need for making your package work, which is why you 
put them in the “suggests” of your DESCRIPTION file. You should _never_ use a library call in your tests 
because that changes the environment from then on and your tests need to be run in a specific order 
to work. Using package::function will give you access to the function without changing your environment.
You should not be using library anywhere in your package except maybe your vignettes.
See hadleys writing on testing: https://r-pkgs.org/testing-design.html_

So, maybe this Issue should be turned around to update all the tests to replace any library calls with packagename::function()? 

I have not yet read the link provided by Ellis, but hope to get to it one of these days. :)  Until then, I hope to hear other opinions on this from @bms63 and  @thomas-neitmann .

**Comment by bms63** [comment]
Many thanks Eric for chasing this.

# Tests

Welll...it is pretty explicit on not using library calls in tests!  Good to know

![image](https://user-images.githubusercontent.com/10111024/189717678-c829c499-4cfd-4230-8359-d073d798c6d5.png)

So if we have the packages in depends/suggest (i.e. tibble and admiral.test) then our tests should just run with no issues?  I just tried this out and it works for the `tribble` function when I add tibble to `@importFrom` in `admiral-package.R` file, but it does not work for `admiral.test`.  It looks like we need to `@export` the datasets in `admiral.test` to have them be available within the namespace for the tests.

Possible ways forward:

The first way:  Add `@export` to `admiral.test` datasets and then load them into `admiral`, but this would make the package larger I think.  However, this means all the testing data is easily accessible and we no longer have to add `library(admiral.test)` or `pkg_name::dataset` to any of the test code

The 2nd way:  Remove library calls and add `tibble::tribble` and `admiral.test::dataset` where needed and not do anything with `@importFrom` for `tibble` or `admiral.test`.  

I'm leaning more to 2nd way as it doesn't increase the size of the package.  We can add to the agenda for Wednesday's meeting to see how we want to proceed for the tests.  

# Examples

I think we are okay to have library call in the examples.   I think this is confusing for new users to see `pkg_name::function` in the examples rather than `library(pkg_name)`, but this is just my personal preference.  I'm happy to change it all up.

![image](https://user-images.githubusercontent.com/10111024/189712115-fc3c1dd0-339e-4320-8d21-329360a607fe.png)

**Comment by bms63** [comment]
Any thoughts @pharmaverse/admiral on testing design?

**Comment by esimms999-gsk** [comment]
@bms63 Thanks for digging up the documentation.

A nice explanation, with an example, from Christina Fillmore at GSK:

_You don’t want to make library calls in your tests cause it will change the environment the tests are run in. So lets say you just used dplyr::mutate() in the package and you never put in an import statement. Then in your tests you called library(dplyr). There wouldn’t be any issues cause all of dplyr would be imported into your environment. But if a user tried to use your package without library(dplyr) it would fail and say function not found. 
You can read more about this [here](https://r-pkgs.org/testing-advanced.html)._

**Comment by esimms999-gsk** [comment]
Modified ~12 files to replace library(packagename) with packagename::function(). These are in PR.

Two left to do, both with library(admiral.test):
test-call_derivation.R
test-deprecation.R (also has library(rlang) and library(tribble). Note that tests are currently failing.
