### ISSUE TITLE
Documentation:  Write vignette on EX processing and last dose date derivation

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#1408]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

We're looking for a real world example of how one would have to pre-process EX data to derive the last dose date before an adverse event. @oreillb1 kindly volunteered to turn her study data into an example that can be showcased on our website.

**Comment by bms63** [comment]
Here is some guidance we have created for writing vignettes. 
 https://pharmaverse.github.io/admiraldev/main/articles/writing_vignettes.html.  @oreillb1 can we put this on the 0.9.0 release track?

**Comment by bms63** [comment]
Hi @oreillb1 do you still have time to create this vignette?

**Comment by oreillb1** [comment]
Yes I have the code already and just need to tidy it up a little and maybe add a couple of comments. Should be ready this week.

**Comment by bms63** [comment]
Fabulous!!

**Comment by oreillb1** [comment]
There is an unexpected  problem with my code using admiral version 0.9.0 because the create_single_dose function running my code now shows 
Error in `assert_data_frame()`:
! Required variables `ASTDT`, `ASTDTM`, `AENDT` and `AENDTM` are missing.
According to the create_single_dose function documentation these are the default values - not mandatory values so something has apparently changed with this function. It no longer matches documentation and does not allow the required ex_single dataframe to be created as required for the last dose derivation in ADAE.
Since `ASTDT`, `ASTDTM`, `AENDT` and `AENDTM` variables cannot be created in EX,  it's necessary to make variables with different names e.g.  start_date = EXSTDT, end_date = EXENDT to include in the ex_single dataframe, and then match up in ad_adae.R  e.g. dose_date = EXSTDT.

**Comment by bundfussr** [comment]
See https://github.com/pharmaverse/admiral/issues/1598

**Comment by oreillb1** [comment]
Issues are resolved and derive_single_dose_fillin.Rmd file is ready

**Comment by bundfussr** [comment]
@oreillb1 , could you create a pull request for merging your feature branch into `devel`?
