### ISSUE TITLE
General Issue: Review collaborators list   

### ISSUE THREAD

**Issue by sadchla-codes** [pharmaverse/admiral#1660]
### Background Information

- [x] Review collaborators list and remove those who have not contributed in over a year.  
- [x] #1696
- [ ] Brainstorm process to review contributor list and purge

### Definition of Done

Have an updated list of collaborators

**Comment by bms63** [comment]
I feel like anyone who is not on this list can just be removed from our collaborators.

https://github.com/pharmaverse/admiral/graphs/contributors.

If someone hasn't committed since the start of 2022, then they can also be removed. 

![image](https://user-images.githubusercontent.com/10111024/210667288-c7417ae7-035d-4229-b41f-e37d0c986b36.png)
