### ISSUE TITLE
General Issue: Allow expressions

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#1727]
### Background Information

Expression should be allowed. The exact scope needs to be defined and functions (in admiral and admiraldev) and documentation updated accordingly.

Also consider deprecating functions, e.g., `derive_var_merged_exist_flag()`.

**Comment by bms63** [comment]
Q2 update?  @thomas-neitmann @bundfussr @rossfarrugia.  Feel like we got quite a bit on our plates right now...and in my cup.

**Comment by rossfarrugia** [comment]
Agree, this is a big one and will have lots of impacts that need to be considered within core package and extensions. We should raise it at the next sponsor/leads meeting so that the other POs all get a heads up it's coming.

**Comment by bundfussr** [comment]
I agree, we should implement it in Q2.

**Comment by rossfarrugia** [comment]
I thought worth to add some more details to this issue given its such a key one and some users may be curious to understand more... so here's the original proposal on this:

At the moment the programming strategy forbids to specify expressions for arguments like `new_vars`, `order`, `set_values_to`. The intention was to avoid that the function calls get too complicated. However, there are more and more use cases where the restriction forces the users to implement work-arounds which are more complicated than specifying the expressions directly.

For example
```
  derive_param_extreme_event(
    adrs,
    dataset_adsl = adsl,
    dataset_source = tu_ext,
    filter_source = TUTESTCD == "TUMIDENT" & TUEVAL == "INVESTIGATOR" & TUSTRESC == "TARGET" & TUDT <= !!ref_var,
    set_values_to = vars(
      PARAMCD = "MDIS",
      PARAM = "Measurable Disease at Baseline by Investigator"
    )
  ) %>%
  mutate(
    SRCDOM = case_when(
      PARAMCD == "MDIS" & AVALC == "Y" ~ "TU",
      TRUE ~ SRCDOM
    ),
    SRCVAR = case_when(
      PARAMCD == "MDIS" & AVALC == "Y" ~ "TUSTRESC",
      TRUE ~ SRCVAR
    ),
    SRCSEQ = case_when(
      PARAMCD == "MDIS" & AVALC == "Y" ~ TUSEQ,
      TRUE ~ SRCSEQ
    )
  )
```
could be simplified to
```
  derive_param_extreme_event(
    adrs,
    dataset_adsl = adsl,
    dataset_source = tu_ext,
    filter_source = TUTESTCD == "TUMIDENT" & TUEVAL == "INVESTIGATOR" & TUSTRESC == "TARGET" & TUDT <= !!ref_var,
    set_values_to = vars(
      PARAMCD = "MDIS",
      PARAM = "Measurable Disease at Baseline by Investigator",
      SRCDOM = if_else(AVALC == "Y", "TU", NA_character_),
      SRCVAR = if_else(AVALC == "Y", "TUSTRESC", NA_character_),
      SRCSEQ = if_else(AVALC == "Y", TUSEQ, NA_integer_),
    )
  )
```
The latter is also less error-prone because if the condition `PARAMCD == "MDIS"` is missed in the first example, the SRC* variables for previously derived parameters are changed as well.
The same applies in the case that `derive_param_extreme_event()` is called and AVAL needs to be derived in addition to AVALC.
Also many examples where imputed dates are required could be simplified. For example:
```
ds_ext <- derive_vars_dt(
  ds,
  dtc = DSSTDTC,
  new_vars_prefix = "DSST"
)

adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ds_ext,
    by_vars = vars(STUDYID, USUBJID),
    new_vars = vars(EOSDT = DSSTDT),
    filter_add = DSCAT == "DISPOSITION EVENT" & DSDECOD != "SCREEN FAILURE"
  )
```
to
```
adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ds,
    by_vars = vars(STUDYID, USUBJID),
    new_vars = vars(EOSDT = convert_dtc_to_dt(DSSTDTC)),
    filter_add = DSCAT == "DISPOSITION EVENT" & DSDECOD != "SCREEN FAILURE"
  )
```
Lifting the restriction was also requested by users see https://github.com/pharmaverse/admiraldev/issues/195.
Without the restriction we could deprecate `derive_var_last_dose_grp()`, `derive_var_merged_cat()`, and `derive_var_merged_character()` as well as the `aval_fun` argument (in `derive_param_exist_flag()` and admiralonco functions).
And admiral would be more in line with dplyr as functions like `mutate()` or `arrange()` do not have this restriction.


**From an existing admiral user perspective there shouldn't be so much impact as the change would be backward compatible. I would though expect our ADaM templates to get updated to make more use of this feature to cut down length of the scripts, and also in the vignettes it would be good to show at least one example of both ways of doing this, so those that still prefer to break things up into smaller steps still could.**
