### ISSUE TITLE
General Issue: derive_var_chg is calculating CHG for baseline records

### ISSUE THREAD

**Issue by YaminiBollu** [pharmaverse/admiral#1876]
### Background Information

when we are using derive_var_chg function to calculate CHG variable, CHG is calculated for baseline records as well and populating ZERO. Generally CHG is calculated only for post baseline records right. please let me know your thoughts.
![image](https://user-images.githubusercontent.com/117985678/234168174-5f353902-81a7-453f-af4d-203e5aba7368.png)

**Comment by bundfussr** [comment]
@YaminiBollu , thanks for creating this issue.

`derive_var_chg()` derives `CHG` for all observations where `BASE` and `AVAL` are not `NA`. We did not restrict the derivation to post-baseline records because:
- Often `CHG` is not derived for baseline records but sometimes it is.
- There is no standard way of identifying post-baseline records.

If you need to restrict the `CHG` derivation to post-baseline records, you can use `restrict_derivation()` in combination with `derive_var_chg()` (see last [example for `restrict_derivation()`](https://pharmaverse.github.io/admiral/cran-release/reference/restrict_derivation.html#ref-examples)).

**Comment by bms63** [comment]
Hi @YaminiBollu.  I believe @bundfussr's answer is sufficient.  Let us know if you need any other help.  Also, feel free to post in Slack channel if you don't want to make an issue.

**Comment by YaminiBollu** [comment]
Thanks Stefan.. Yes Ben I am good.
