### ISSUE TITLE
Feature Request:  Run testthat in parallel

### ISSUE THREAD

**Issue by StefanThoma** [pharmaverse/admiral#1916]
### Feature Idea

I just found out that we could run the tests in parallel. 
At the moment, it adds some time to the `devtools::check()` command (1m 24.9s for me). 
It looks like it would be really easy to implement, see: 
https://testthat.r-lib.org/articles/parallel.html

@pharmaverse/admiral does anyone see any downside?

**Comment by esimms999-gsk** [comment]
@StefanThoma Beautiful! I love this stuff! I had a quick look.

The good news: nothing seems to be falling over when using parallel testing. This is good to know regardless, because it gives some confidence that our tests are not impacting the environment.

Results with my quick evaluation of this: 

- 1 process (what we have always been using): ~65 seconds 
- 2 processes (the default for parallel): ~57 seconds
- 3 processes: ~61 seconds
- 4 process: ~66 seconds
- 8 processes: ~77 seconds

Maybe this increase in time with 3 or more processes is due to the large number of quick tests we have in admiral: "This overhead generally means that if you have many test files that take a short amount of time, you’re unlikely to see a huge benefit by using parallel tests."
From this quick evaluation, it looks like we can save some time by using parallel testing with TESTTHAT_CPUS=2.

**Comment by esimms999** [comment]
No need to specify TESTTHAT_CPUS=2; that is the default if we have ```Config/testthat/parallel: true``` in the DESCRIPTION file.

**Comment by esimms999-gsk** [comment]
Having looked into this a bit more, I think it would not be a good decision to make use of parallel testing. 

The benefit seems to be very small (<15% of testing time saved, which is just a few seconds). 

Another benefit is that by doing parallel testing, you can surface problems where one test is depending on another and an error occurs because of this; the test could be re-written and improved due to this finding. While this would be a good thing, it is random and I don't think we could evaluate all possibilities. This could mean that a developer with a different number of CPU's assigned for parallel testing could be the first one to see an error.
