### ISSUE TITLE
General Issue: `derive_var_obs_number`  treat missing values `NA` a little different with SAS

### ISSUE THREAD

**Issue by ynsec37** [pharmaverse/admiral#2257]
### Background Information

[`dplyr::arrange`](https://dplyr.tidyverse.org/reference/arrange.html), NA are: always sorted to the end for local data, even when wrapped with `dplyr::desc()`. 

SAS `PROC SORT`: a missing value for a numeric variable is smaller than all numbers. Missing values of character variables are smaller than any printable character value.

### Definition of Done

I just want to confirm that it is necessary  to consider the missing values when sorting data, as the missing values do not seem so important.

Please see the following example.
``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 4.2.3
library(admiral)
#> Warning: package 'admiral' was built under R version 4.2.3
vs <- tribble(
  ~STUDYID, ~DOMAIN,      ~USUBJID, ~VSTESTCD, ~VISITNUM, ~VSTPTNUM,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,        NA,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,       815,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,       816,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         4,       815,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         4,       816
)

vs %>%
  derive_var_obs_number(
    by_vars = exprs(USUBJID, VSTESTCD),
    order = exprs(VISITNUM, VSTPTNUM)
  )
#> # A tibble: 5 × 7
#>   STUDYID DOMAIN USUBJID     VSTESTCD VISITNUM VSTPTNUM  ASEQ
#>   <chr>   <chr>  <chr>       <chr>       <dbl>    <dbl> <int>
#> 1 PILOT01 VS     01-703-1182 DIABP           3      815     1
#> 2 PILOT01 VS     01-703-1182 DIABP           3      816     2
#> 3 PILOT01 VS     01-703-1182 DIABP           3       NA     3
#> 4 PILOT01 VS     01-703-1182 DIABP           4      815     4
#> 5 PILOT01 VS     01-703-1182 DIABP           4      816     5
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Reproduct example from SAS
```SAS
data vs;
    infile datalines dsd truncover;
    input STUDYID:$7. DOMAIN:$2. USUBJID:$11. VSTESTCD:$5. VISITNUM:32. VSTPTNUM:32.;
    label ;
datalines;
"PILOT01","VS","01-703-1182","DIABP",3,
"PILOT01","VS","01-703-1182","DIABP",3,815
"PILOT01","VS","01-703-1182","DIABP",3,816
"PILOT01","VS","01-703-1182","DIABP",4,815
"PILOT01","VS","01-703-1182","DIABP",4,816
;;;;
run;

proc sort data=vs out=vs_2;
    by USUBJID VSTESTCD VISITNUM VSTPTNUM;
run;

data vs_3;
    set vs_2;
    by USUBJID VSTESTCD VISITNUM VSTPTNUM;
    if first.VSTESTCD then ASEQ = 0;
    ASEQ + 1;
run;    
```
![vs](https://github.com/pharmaverse/admiral/assets/98389771/09cf2320-6db0-4170-ae75-e7e7f3faa6b5)

**Comment by manciniedoardo** [comment]
HI @ynsec37, thanks for reaching out with this question.

As you have noted, the issue at heart here is that `dplyr::arrange()` and `proc sort` behave differently when sorting `NA` values. Though SAS places them at the start, the [documentation for `arrange()`](https://dplyr.tidyverse.org/reference/arrange.html) states: _"Unlike base sorting with `sort()`, `NA` are always sorted to the end for local data, even when wrapped with `desc()`."_ Since {admiral} depends on {dplyr}, this is why you are observing this behaviour in `derive_var_obs_number()`.

My opinion: ADaM standards should be language agnostic, and as long as the supporting documentation is clear, it is natural that we can observe small differences in implementation across programming languages. Indeed we have already seen (and made peace with) a similar case with [rounding](https://github.com/pharmaverse/admiral/issues/1872), where R rounds to the nearest even whereas SAS rounds up. In the [ADaM IG](https://wiki.cdisc.org/download/attachments/54282867/ADaMIG-ADaMIG-compiled-191217-0027-11448.pdf?version=1&modificationDate=1520419159850&api=v2), we find that: _"Sequence number given to ensure uniqueness of subject records within an ADaM dataset. As long as values are unique within a subject within the dataset, any valid number can be used for ASEQ. ASEQ uniquely indexes records within a subject within an ADaM dataset."_ So, essentially, sequence variables essentially serve to give unique keys to the data when all other keys are matching, thus the placement of NA variables in this case shouldn't make a noticeable difference. 

 At the end of the day, I think this is an acceptable difference between the R and SAS approach.

**Comment by bundfussr** [comment]
Hi @ynsec37 , the `order` argument of the admiral functions accept expressions. This allows you to specify explicitly how `NA` should be treated. For example, the following call sorts `NA` to the start (like SAS).
```
> vs %>%
+     derive_var_obs_number(
+         by_vars = exprs(USUBJID, VSTESTCD),
+         order = exprs(VISITNUM, if_else(is.na(VSTPTNUM), -Inf, VSTPTNUM))
+     )
# A tibble: 5 × 7
  STUDYID DOMAIN USUBJID     VSTESTCD VISITNUM VSTPTNUM  ASEQ
  <chr>   <chr>  <chr>       <chr>       <dbl>    <dbl> <int>
1 PILOT01 VS     01-703-1182 DIABP           3       NA     1
2 PILOT01 VS     01-703-1182 DIABP           3      815     2
3 PILOT01 VS     01-703-1182 DIABP           3      816     3
4 PILOT01 VS     01-703-1182 DIABP           4      815     4
5 PILOT01 VS     01-703-1182 DIABP           4      816     5
```
I would always specify explicitly the handling of `NA`s for order variables where `NA`s are expected.

**Comment by bms63** [comment]
Shall we add this in as an example for this function?

**Comment by ynsec37** [comment]
Hi @manciniedoardo  and @bundfussr, thanks much for your reply
> order argument of the admiral functions accepts expressions

For ascending sort, we can add a `!is.NA()` to make the `NA` smallest first, it can work both for numeric and character

``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: package 'dplyr' was built under R version 4.2.3

library(admiral)
#> Warning: package 'admiral' was built under R version 4.2.3

vs <- tribble(
  ~STUDYID, ~DOMAIN,      ~USUBJID, ~VSTESTCD, ~VISITNUM, ~VSTPTNUM,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,        NA,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,       815,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         3,       816,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         4,       815,
  "PILOT01",    "VS", "01-703-1182",   "DIABP",         4,       816
)


# For ascending order, add extra `!is.na()` make the NA smallest
vs %>% dplyr::group_by(USUBJID, VSTESTCD) %>% 
  dplyr::arrange(VISITNUM, !is.na(VSTPTNUM), VSTPTNUM)
#> # A tibble: 5 × 6
#> # Groups:   USUBJID, VSTESTCD [1]
#>   STUDYID DOMAIN USUBJID     VSTESTCD VISITNUM VSTPTNUM
#>   <chr>   <chr>  <chr>       <chr>       <dbl>    <dbl>
#> 1 PILOT01 VS     01-703-1182 DIABP           3       NA
#> 2 PILOT01 VS     01-703-1182 DIABP           3      815
#> 3 PILOT01 VS     01-703-1182 DIABP           3      816
#> 4 PILOT01 VS     01-703-1182 DIABP           4      815
#> 5 PILOT01 VS     01-703-1182 DIABP           4      816

vs %>%
  derive_var_obs_number(
    by_vars = exprs(USUBJID, VSTESTCD),
    order = exprs(VISITNUM, !is.na(VSTPTNUM), VSTPTNUM)
  )
#> # A tibble: 5 × 7
#>   STUDYID DOMAIN USUBJID     VSTESTCD VISITNUM VSTPTNUM  ASEQ
#>   <chr>   <chr>  <chr>       <chr>       <dbl>    <dbl> <int>
#> 1 PILOT01 VS     01-703-1182 DIABP           3       NA     1
#> 2 PILOT01 VS     01-703-1182 DIABP           3      815     2
#> 3 PILOT01 VS     01-703-1182 DIABP           3      816     3
#> 4 PILOT01 VS     01-703-1182 DIABP           4      815     4
#> 5 PILOT01 VS     01-703-1182 DIABP           4      816     5
```

<sup>Created on 2023-11-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bundfussr** [comment]
> Shall we add this in as an example for this function?

Yes, it is a good idea to provide this information. However, it does not affect `derive_var_obs_number()` only. It affects all functions with an `order` argument.
What about adding a section to the "Generic Derivations" vignette and then add a link referring to the section to the description of the `order` argument?

**Comment by bms63** [comment]
I like the addition to the Generic vignette.

This also sounds like a great blog post for the pharmaverse blog!!

**Comment by bundfussr** [comment]
OK, I'll add it to the vignette (I need to add some new functions anyway.).
