### ISSUE TITLE
General Issue: Test for `tests/testthat/test-derive_var_obs_number.R` is same as `tests/testthat/test-filter_extreme.R`

### ISSUE THREAD

**Issue by ynsec37** [pharmaverse/admiral#2260]
### Background Information

Dear developers, 

The two tests file are same

[tests/testthat/test-derive_var_obs_number.R](https://github.com/pharmaverse/admiral/blob/main/tests/testthat/test-derive_var_obs_number.R)

[tests/testthat/test-filter_extreme.R](https://github.com/pharmaverse/admiral/blob/main/tests/testthat/test-filter_extreme.R)

**Comment by bms63** [comment]
Interesting!!

So all our tests of other functions cover this function so that is good news!

![image](https://github.com/pharmaverse/admiral/assets/10111024/56e0671d-7853-4b70-ab2d-b5586c43a54c)


However, should we make a dedicated test for this `derive_var_obs_number` or just delete the test file.  I'm leaning towards making a dedicated file with some different scenarios.

@pharmaverse/admiral

**Comment by bms63** [comment]
@ynsec37 would you like to make a test for this function?  If not, I will take on!  

Thanks for all your great spots and discussions!!!!!!!

**Comment by ynsec37** [comment]
Hi @bms63, I had created a draft pull request. https://github.com/pharmaverse/admiral/pull/2267
some check lists may be not applicable and unticked, please help to review. Thanks
