### ISSUE TITLE
General Issue: Move functions argument to the next phase of deprecation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#2299]
### Background Information

We have a few function arguments that need to be progressed in their stage of deprecations.

![image](https://github.com/pharmaverse/admiral/assets/10111024/6776f41c-1b7e-4f36-b22f-b2db6bec2bd5)

### Definition of Done

- [ ] The above screenshotted function arguments are moved along in the deprecation process
- [ ] Double check that these functions have been removed from admiral 
![image](https://github.com/pharmaverse/admiral/assets/10111024/76f522e2-4209-4010-b6b3-5a6746aa7a5d)

- [ ] Check that none of the deprecated arguments are being used in templates/vignettes.

**Comment by bms63** [comment]
@pharmaverse/admiral hey all!!  A nice easy one to start off the new year!!

**Comment by ddsjoberg** [comment]
@bms63 I started on the first deprecation: `compute_gfr(wt)`, and I want to make sure I am understanding the next steps properly.

By reviewing the NEWS, it seems that we are warning users that a deprecation _will_ occur in the next release, rather than a note that we've deprecated at item, correct? Typically, the NEWS aligns with what we've done in that release. For example, instead of saying that the following function arguments _are entering_  the next phase of deprecation, I would expect it to say, the `compute_gfr(wt)` argument is now defunct and has been removed from the package (and the argument would no longer appear in the v1.0.0 release).

Just an FYI, we can chat about deprecation cycles in one of our meetings coming up!

**Comment by bms63** [comment]
In the past we have done a three-staged approach to deprecation.  

First stage we have the function issue a warning message telling the user that the function is deprecated with recommended updates.  Second stage we have function issue an error message.  Third stage we completely remove the function from admiral.

It generally took us 9 months for a function or argument to be completely purged from admiral!  Now with later cycle times, it could be quite while until something is removed.

I put in a Discussion item https://github.com/pharmaverse/admiral/discussions/2191#discussioncomment-8079967
