### ISSUE TITLE
update ADPC template: ATPT="Pre-dose" assigned 3 different values of ATPTN

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiral#2328]
### Background Information

Issues raised by @botsp from `pharmaverseadam`: https://github.com/pharmaverse/pharmaverseadam/issues/58

ADPC: ATPT="Pre-dose" assigned 3 different values of ATPTN(-0.5,24,48).

![image](https://github.com/pharmaverse/admiral/assets/47867131/1c311189-dc69-4671-8cbc-921e7365a2dd)

### Definition of Done

change `ATPT` from "Pre-dose" to "xxh Post-dose" when `ATPTN =24/48` and  `DTYPE="COPY"`  by updating the assignment below: 

https://github.com/pharmaverse/admiral/blob/16671ee64d124e9eff26bfa7a776442ad610ed84/inst/templates/ad_adpc.R#L424

**Comment by bms63** [comment]
@jeffreyad do you find fixing this issue while making your updates to ADPC/ADPP templates? please and many thanks you!!!

**Comment by jeffreyad** [comment]
@kaz462 thanks.  The `ATPT` should be `Pre-dose` for these records since they are for "Duplicated Records for Analysis." However, I could update `ATPTN` to -.5 to match the original values of `PCTPTNUM` for the `Pre-dose` records.  See page 19 of CDISC ADaMIG for Non-compartmental Analysis Input Data v1.0.

![image](https://github.com/pharmaverse/admiral/assets/112705781/ac62705b-761e-4e6c-8c4e-1bf045cba21a)


https://www.cdisc.org/standards/foundational/adam/adamig-non-compartmental-analysis-input-data-v1-0

**Comment by kaz462** [comment]
@jeffreyad good to know, thanks for the background information!
