### ISSUE TITLE
create a stack overflow forum (4h)

### ISSUE THREAD

**Issue by koegerr** [pharmaverse/admiral#361]
create and link with the Analytical Data Science Community at Roche/GSK

**Comment by bms63** [comment]
Hey Robin -

Could we just create a custom tag for admiral and pharmaverse?    We also have our slack channel as a stand-in.  Maybe we need this to be sponsored by the pharmaverse rather than admiral specific.  

![image](https://user-images.githubusercontent.com/10111024/150353183-cc638b84-09b7-4618-8cc2-98d45fbaa75f.png)

**Comment by thomas-neitmann** [comment]
That's actually what we had in mind (at least for the "admiral" tag but I agree having "pharmaverse" as well is a good idea). Creating new tags does require a certain amount of reputation on SO but I'm pretty sure I have enough to do so.
