### ISSUE TITLE
Create SAS-like format functionality

### ISSUE THREAD

**Issue by thomas-neitmann** [pharmaverse/admiral#409]

**Comment by bms63** [comment]
This will be handled by the xportr package going forward.  Can we close this issue out.

**Comment by bundfussr** [comment]
I think this issue is not about setting the format in the SAS dataset (, which will be handled by xportr) but about providing a similar functionality like `proc format` and `put()` or `input()` in SAS. This could be helpful for many derivations, e.g., grouping variables, numeric variables related to categorical variables, visits based on time windows, ...

Thus I would not close it.

**Comment by statasaurus** [comment]
This is handled in the metatools package. But if the function in metatools does not meet expectation please add the issue there.
