### ISSUE TITLE
derive_last_dose fails for medications reported as interval

### ISSUE THREAD

**Issue by otts5** [pharmaverse/admiral#626]
Hi,
the function derive_last_dose() that I want to use for ADAE fails because I have some medication in EX reported as intervals, i.e. the start and end date are not the same. I can see the problem with a time interval spanning multiple days, but it's not ok that the function stops working completely if something is identified. There can be a note and maybe a parameter saying, use the EXENDTC no matter what (as it is done by STREAM) or exclude multiple day intervals. I would actually only exclude intervals over more than one day. You might have an infusion that starts before midnight and finishes the next day. In that case it's totally fine to use EXENDTC.

Thanks,
Sandra

**Comment by otts5** [comment]
Hi @bundfussr what would the function do, if EXDOSFRQ is not 'ONCE'? Resume, but simply not derive the date? It should definitely not fail as it does now.

**Comment by bundfussr** [comment]
Hi @otts5 , if the condition is not fulfilled, the function will fail because user input is required to fix the issue. Either the exposure input dataset needs to be changed or the condition modified.

We discussed the topic today in the developer team and decided that we implement the `single_dose_condition` parameter and provide a separate function which transforms a multi dose exposure dataset to a single dose exposure dataset.

**Comment by thomas-neitmann** [comment]
@otts5 Just to add some more details. What we discussed in our dev meeting yesterday was to continue to expect a dataset with one row per dose as input for `derive_last_dose()`. However, because exposure is rarely collected like that, we want to develop some transformation functions that "expands" datasets collected with other frequencies, e.g. `"Q2W"`, into a one-dose-per-row dataset.

**Comment by otts5** [comment]
@bundfussr @thomas-neitmann Thanks for the explanation. I still think that the function should not fail and break the whole program. What would I do if I can't fix the data as it might be the case for old studies?

**Comment by bundfussr** [comment]
@otts5 , if you can not fix the data, you could set `single_dose_condition = TRUE` in the `derive_last_dose()` call. Then the check always passes and the function no longer fails.

**Comment by otts5** [comment]
@bundfussr Ok, I see. Thanks.

**Comment by bms63** [comment]
See #660
