### ISSUE TITLE
Should admiral provide a framework, e.g., for grouping deriviations?

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#728]
Should admiral provide a framework or grouping functionality to avoid that admiral function calls are copied from script to script, datacut to datacut, study to study, ...?

**Comment by rossfarrugia** [comment]
@bundfussr I'd be interested to hear more on this idea when you get back after holiday. I think you're talking about some kind of inheritance where you could define admiral calls at a higher level than reporting event, such as company or molecule level. If so I think that is more a company-specific discussion rather than something for the admiral package.

**Comment by thomas-neitmann** [comment]
Closing as out of scope of admiral.
