### ISSUE TITLE
TTE vignette comments

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiral#757]
Hi team,
Some comments spotted when reviewing https://roche-gsk.github.io/admiral/articles/bds_tte.html:

1. it would be nice to show an example call when using one of the "Pre-Defined Time-to-Event Source Objects"
2. out of interest is the plan to extend this offering of pre-defined objects to maybe include standard efficacy endpoints like OS and PFS?
3. in the examples where you start to show OS and PFS the start_date is still TRTSDT whereas for efficacy I'd expect to always use RANDDT here, but do ignore me if that's just a Roche-ism and not matching CDISC

**Comment by bundfussr** [comment]
I completely agree to your first point.

For OS you could use the predefined objects `death_event` and `lastalive_censor` like in the example. It would be nice to have more pre-defined objects but it is hard to realize because other endpoints are usually based on other ADaM datasets like ADRS, ADQS, .... As the values of PARAMCD and AVAL are not standardized, we can not define objects for endpoint like PFS on admiral level. We could define them in admiral.roche.

Regarding the start date I am fine with changing TRTSDT to RANDDT. There is no CDISC guidance for the start date. Roche uses RANDDT for randomized studies and TRTSDT for non-randomized studies. So using RANDDT may be the more common case.

**Comment by thomas-neitmann** [comment]
Another issue you want to take on @rossfarrugia 😉

**Comment by rossfarrugia** [comment]
thanks @bundfussr - that makes sense. for point 2 i guess an option for admiral.roche as you say for now or even some global admiral package extension later when we start to cover specific TA endpoints and try to align them at industry-level. that's where HAs surely would hope we can take this. good discussions for 2022!

for point 3, the usual rationale is efficacy analysis would more likely use ITT population so may include patients without treatment received, and endpoints like this are most focused to Ph II or III studies where most commonly there would be randomization. so all in all, not a big deal but i think changing to RANDDT here would resonate more with most programmers reading it. it's only an example though and users have to do what's right for them.

@thomas-neitmann let's see how my first contribution goes before getting ahead of myself and then maybe i gain confidence later... :)

**Comment by rossfarrugia** [comment]
@bundfussr i'll make these updates

**Comment by rossfarrugia** [comment]
@bundfussr there's no randdt in the CDISC test data ADSL so i'll just add a note instead of changing for point 3
