### ISSUE TITLE
new functions for AE variables

### ISSUE THREAD

**Issue by donyunardi** [pharmaverse/admiral#841]
This is my issue so first, thanks for working on this amazing package!
My team and I have started to use admiral in our pipeline and it has been a great experience so far.

Sandra Ott from my team created two new functions to assist her in creating two variables in ADAE:
* astdtm
* trtemfl

We were wondering if this would be useful and within the scope of the admiral package.
I'll start the issue as a start and create the branch for review.

**Comment by thomas-neitmann** [comment]
Thanks a lot for creating yout first issue, @donyunardi. Much appreciated!

This certainly does look like it's in scope of admiral. I'm just wondering if these variables are not already covered by existing (general) functions. Anyhow, if the code is already there, then it's best if you open a PR and someone from the team can take a look.

@pharmaverse/admiral Feel free to chime in.

**Comment by donyunardi** [comment]
Thanks @thomas-neitmann !
I'll create the PR as you suggested.

**Comment by rossfarrugia** [comment]
@thomas-neitmann @donyunardi – I did some chasing up on Slack and speaking to @bundfussr and I suggest the following action:

- ADAE.ASTDTM – let’s leave this to the #727 updates to cover with added flexibility to the existing function, and for any final Roche-specifics that are not covered myself and Stefan will take to our Roche standards group to consider changes; otherwise we’d do this at {admiral.roche}

- ADAE.TRTEMFL – there’s encouragement from the community that this is needed in {admiral}. I’ve compared our Roche specs vs an industry paper https://www.lexjansen.com/phuse/2017/dh/DH10.pdf, and i would suggest the following approach for derive_var_adae_trtemfl:

**Description:** An event that emerges during treatment having been absent pre-treatment, or worsens relative to the pre-treatment state. This derivation assumes AE data collection method as single record per AE with “initial” and “most extreme” severity/intensity recorded separately.

**Specs** (simplified from Roche version to start, e.g. no FA pieces as i don't think would be relevant to most): 
Set to "Y", if the Analysis Start Date/Time [ADAE.ASTDTM] is at or after Datetime of First Exposure to Treatment [ADSL.TRTSDTM].
   Else set to null, if the Analysis End Date/Time [ADAE.AENDTM] is before Datetime of First Exposure to Treatment [ADSL.TRTSDTM].
   Else set to "Y", if Analysis Start Date/Time [ADAE.ASTDTM] is before Datetime of First Exposure to Treatment [ADSL.TRTSDTM] but Analysis End Date/Time [ADAE.AENDTM] is either missing or after Datetime of First Exposure to Treatment [ADSL.TRTSDTM] and either the most extreme Severity/Intensity [AE.AESEV] is greater than Initial Severity/Intensity [AE.AESEVIN] or either Initial Severity/Intensity [AE.AESEVIN] or most extreme Severity/Intensity [AE.AESEV] (or both) is missing.
   Else set to null, if the Analysis Start Date/Time [ADAE.ASTDTM] is before Datetime of First Exposure to Treatment [ADSL.TRTSDTM].
   Set to "Y" otherwise.

**Function Arguments:**
- Need an option to use toxicity grade (AEITOXGR and AETOXGR) instead of severity
- Ability to choose a start date of treatment period to use, e.g. TRTSDTM
- Option to add an end date of treatment period, and if so nothing starting after this date would get flagged. User may want to do TRTEDTM+42 here if we'd allow for that

@bundfussr - what do you think? and @bms63 if you have any experience from GSK side and your specs for this please add too.

**Comment by bundfussr** [comment]
Thanks @rossfarrugia , looks good to me.

Just one point: At the moment the admiral programming strategy does not allow to specify expressions like `TRTEDTM + 42`. Thus we would need two parameters, one for the end date and another one for the length of the time window.

**Comment by rossfarrugia** [comment]
makes sense Stefan, that's fine!

@donyunardi - are you or Sandra interested in making the updates to the code you submitted in the PR to generalise it more in line with the admiral needs above? let us know and if not we could try and find someone to pick up using your TRTEMFL code as a starting point.

**Comment by bundfussr** [comment]
It should be possible to specify more than one end date for the derivation of the treatment emergent flag, e.g., treatment end + x days and start of next period. Whatever comes first is used in the derivation.

**Comment by bundfussr** [comment]
We discussed this issue in the "Questions and Comments" meeting and decided get feedback from GSK and other companies regarding these derivations.

**Comment by teckla-gsk** [comment]
GSK does consider worsening severity in the determination of treatment emergence as below:
In regards to worsening, there are some unique scenarios that need to be considered:
1.	if an AE occurs before treatment and then worsens while on treatment, then it should be treatment emergent. 
2.	Also in a cross over, if the AE first occurred on TRT A and then worsened while on TRT B, then the AE would be flagged as treatment emergent within both treatment groups. And it may be study specific for how start/end dates are derived based on this. 
So maybe an update to the ontrt function?

**Comment by rossfarrugia** [comment]
Thanks @teckla-gsk - good to hear about point 1. For point 2 personally I wouldn't add that flexibility in the function as it is so specific to a protocol design and there's many different ways periods of a study could affect derivations like this (e.g. see the phuse paper linked above). When I discussed with @bundfussr this before he suggested maybe something like https://github.com/pharmaverse/admiral/issues/701 could give the user control of specific cases like this.
On a related note, I do think longer term a vignette around crossover studies would be a nice idea to add, giving examples like this and how something like slice_derivation could achieve common crossover analyses needs.

**Comment by bundfussr** [comment]
Should we implement a `compute_relation()` function which returns the relation (`"before"`, `"within"`, `"after"`) of a time point and a period or the relation (`"before"`, `"before_within"`, `"within"`, `"before_within_after"`, `"within_after"`, `"after"`) of two periods?
It could be helpful for derivations like `ONTRTFL`, `TRTEMFL`,  and `ATIREL`.

**Comment by thomas-neitmann** [comment]
Sounds like a good idea to me @bundfussr 👍

**Comment by donyunardi** [comment]
Hi @rossfarrugia,
Sorry for the late reply, but yes, let me discuss this with Sandra and we'll update the code.

**Comment by millerg23** [comment]
Hi @donyunardi,

I opened a new issue for TRTEMFL derivation https://github.com/pharmaverse/admiral/issues/989

Once you or Sandra are ready to take this on, feel free to contact me, we had a few discussions in the team about how to go about this.

Many thanks.

**Comment by koegerr** [comment]
closing according to Gordons new : TRTEMFL derivation https://github.com/pharmaverse/admiral/issues/989
