### ISSUE TITLE
Create general age group function

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#856]
Create a general age group function (custom age groups and unit conversion). deive_vars_agegr_ema and derive_vars_agegr_fda should be wrapper functions of the general function.

Decision: remove `derive_vars_agegr_fda|ema()` do not create a general age group function but keep `derive_var_age_years()`

**Comment by rossfarrugia** [comment]
Adding an example function call of how this could look that Gordon shared with me for whoever picks this up:

derive_var_agegr(
  sourve_var = AAGE,
  new_var = AGEGR1,
  grouping_map = get_map(
    0 - 64 := "<65",
    65 - inf := ">=65")
)

Reminder would need same updates then in ADSL template and vignette

**Comment by rossfarrugia** [comment]
Question for the core team to consider: is this really worth it when the user could just create a simple user function for their needs using case_when like in our ADSL vignette example: https://pharmaverse.github.io/admiral/articles/adsl.html?search-input=ADAE#derive-groupings-and-populations. Would we just be creating our own admiral version of case_when by creating get_map() ?

Plus in our prog strategy we have: _Parameter must not accept expressions for assigning the value of the new variable_

@koegerr any thoughts?

**Comment by bundfussr** [comment]
The `derive_var_agegr()` function should also take different units of the age variable into account (like `derive_ver_agegr_ema()` does).

The intention of `get_map()` is to improve the readability of the definition and and include the definition in the object. I.e., a map object does not require additional documentation as it is contained in the object (see https://github.com/pharmaverse/admiral/issues/1021 for examples).

**Comment by koegerr** [comment]
I am not sure if it is a good idea to create more helper functions that sit in other functions if it is purely about conditioning (case when ...).
One of the problems about this is usually that we create too many layers and code becomes difficult to read or understand. 

basic joins, or if then else conditions should not be wrapped up too much. Simplicity is the key benefit of admiral. Creating too general functions I feel we will lose this simplicity.

My suggestion is to take a step back here and wait till Thomas is back and have a general discussion around this.

**Comment by bundfussr** [comment]
The intention is not to implement more helper functions or create additional layers. The intention is to simplify the creation of user specific helper functions which act like SAS formats.

For example if users need to define an age grouping, they could define a function like the following.
```
#’ Age group
#’
#’ …
#’ 
#’ @param arg …
#’
age_group_65 <- function(arg){
  assert_numeric_vector(arg)

  case_when(
  !is.na(arg) & arg < 65 ~ "< 65",
  arg >= 65 ~ ">= 65",
  TRUE ~ NA_character_
 )
```

The idea of `get_map()` is that technicalities like name of the argument, checking input values, returning `NA` for not covered values, documentation, ... are handled by `get_map()` and the users just need to provide the essential information namely the values on the left hand side and the values on the right hand side.

I would consider
```
age_group_65 <- get_map(
0 - 64 := "<65",
65 - inf := ">=65")
```
as shorter and more readable than the function definition above. Additionally `get_map()` could check the validity of the input. E.g., it could issue a warning or error of a value on the left hand side occurs more than once.

Of course, the users need to know how to use `get_map()`. But I think the usage is very intuitive. So it should not require much time and as functions like these are required frequently it is worth the effort.

Furthermore, it could also help to convince users that using R instead of SAS is beneficial. I think most users would consider implementing a function using `case_when()` as a setback compared to SAS formats while using `get_map()` would be considered as an improvement.

The topic is already on the agenda of the Monday meeting. I hope Thomas will be back then.

**Comment by esimms999-gsk** [comment]
I have been doing some digging on the age ranges. It looks to me that this is all over the place and the GSK specs state that this is "study-specific". One study I looked at has age categorized as "<35", "35 - <50", ">=50". We often use "<18", "18 - <65", ">=65" but I have not found a standard anywhere for CDISC except the following, which is fuzzy about where 65 lands:

![NCI_Age_Groups](https://user-images.githubusercontent.com/85294667/160634971-02dc380e-e099-472d-8b1f-ce96d4485a9f.jpg)

I think getting rid of the hard-coded functions (e.g. derive_vars_agegr_fda), explicitly stating that the ranges need to be provided as per the SAP and providing examples of get_map is the way to go.

**Comment by aehmann-gsk** [comment]
@esimms999-gsk The EMA and FDA functions support study disclosure requirements.  These particular age groups will more than likely never be used in analysis.  For the US disclosure requirements, please see:
https://prsinfo.clinicaltrials.gov/results_definitions.html

In particular:
![image](https://user-images.githubusercontent.com/82041175/162201015-f0596d79-2840-46a4-9605-4c2dbc3b5c9b.png)

@statasaurus has already programmed a function which will do categorization based on a CT code list (similar to what is being proposed).  This is currently resides in `metacore`.  I am in favor of retiring the FDA/EMA functions but would like the `metacore` functionality for categorizing values included in `admiral`. The current implementation of `derive_var_agegr_fda` will result in incorrect results at GSK since GSK utilizes the categorization provided in the `results_definitions.html`.

We should work together and either that functionality should be used from `metacore` or a small part of that functionality could be moved to admiral from `metacore` and then `metacore` could call `admiral`.  Regardless, we need to ensure we are not duplicating functionality and coding across packages in `pharmaverse`.

**Comment by aehmann-gsk** [comment]
I think it is a bit of duplication.  The CT should align for the AGEGR* variables and for the define.  All of these things are linked. I am not sure why we would treat age groups differently than other groupings such as a BMI baseline group.  

This is a CT list:
```
age_group_65 <- get_map(
0 - 64 := "<65",
65 - inf := ">=65")
```

**Comment by statasaurus** [comment]
> I think there is no duplication. The admiral function takes the unit of the age variable into account and converts to years if necessary. I guess the metatool function is not doing this.
> 
> In admiral I would create a general age group function, deprecate the specific ones, and provide map objects for FDA and EMA disclosure age groups. Company specific map objects can be provided by company-specific admiral packages.

Given the pharmaverse is ideally a cohesive group of packages, I am a bit worried about confusing the end user if they are too close. I am not 100% sure of what the best way to check for units is. But, I think it is fair to want that and we can look at adding that into the metatools functions

**Comment by aehmann-gsk** [comment]
Why can't the unit checking be part of a specific age function in admiral? Unit check first, then use metacore to apply mappings and code/decodes?  I feel like there are 2 functions to calculating age groups.  In theory, the unit checking could be applicable to other things as well such as dosing, lab values, etc..

**Comment by statasaurus** [comment]
Metacore would work of a spec document. So yes most the time you won't be building from a define. Also there are a couple of layers that to do this. At the lowest level users can use [`create_subgrps` ](https://pharmaverse.github.io/metatools/reference/create_subgrps.html)
which will work inside a mutate statement so the workflow would more or less be 
` adsl %>% 
mutate(AGEGR1 = create_subgrps(AAGE, c("<65", ">=65"))
`

**Comment by bundfussr** [comment]
I would move `create_subgrps()` to admiral and rename it to `compute_subgrps()`. Otherwise, users who do not use a metacore object would need to use metatools. This could be confusing.

**Comment by statasaurus** [comment]
Because of the size of the packages I think it is better to leave the function where it is. At the moment meta tools is a very small package with very dependancies. It would be better to just have admiral export the function. That way the user still be able to call the function through admiral, like how you can use the pipe in dplyr

**Comment by rossfarrugia** [comment]
hi all, i asked Robin to take a look when he gets chance too and comment, but my recommendation would be leave the feature in both. It's inevitable with such closely connected packages that at times there'll be some overlap and they'll never be seen as in competition - it just provides the users a choice dependent on which selection of packages they're using. 

My rationale for this is as follows:
- we always agreed admiral would not be dependent on metacore/metatools as the idea was we enable companies to use whichever packages fit their needs, rather than saying you need to adopt all e2e pharmaverse packages, as that would limit adoption.
- as Stefan points out, people won't always have specs for this, e.g. admiral is often used by exploratory users such as BioStats, but they would still have the need to apply grouping as part of derivations so admiral needs to offer this.
- this way admiral documentation could continue to focus on admiral (or tidyverse) functions and the e2e pharmaverse site could show how it could work when using metacore/metatools as well.

p.s. i do think it's a cool option in metatools and for companies that adopt this package i do like the feature of the groupings provided in the spec driving what gets applied to the data.

**Comment by rossfarrugia** [comment]
FYI all we discussed in admiral team meeting today and agreed no need to add a general age group function in admiral. People can either use case_when as in our ADSL vignette examples or use the options from metatools. Rationale: we discussed in depth and came to conclusion this grouping can be achieved so simply it doesn't really warrant an admiral function anyway. 
I take back my comment above!

**Comment by koegerr** [comment]
Thomas and myself discussed and will close this issue with the rational given in the comment from Ross.
