### ISSUE TITLE
Should we start the scooter?

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#862]
One year ago I had my first admiral meeting. Maybe this is a good time to look back.

In one of the first meetings with GSK Suhas presented the following picture of our development process.
![image](https://user-images.githubusercontent.com/80953585/151959266-8d6fa18c-6095-4ed7-ae95-ca64dd9d52ef.png)

In the past year we achieved a lot working on the skateboard. However, it seems that we have been drifting off from our original approach. Thus I wonder if we should start working on the scooter.

The original approach assumed that an ADaM dataset is built by calling functions like `derive_var_<var name>()` and `derive_param_<parameter code>()`. The structure of the functions should be flat, i.e., they should not call other admiral functions but just base R or dplyr functions.

During the development and based on testers feedback we realized that the approach is a bit too simple and we made the admiral functions more and more general. This has been resulting in repeated updates of functions and frequent discussions regarding the design of the functions. Furthermore, providing more general functions makes it hard for users to find the functions they need. I think at the moment there is a conflict between sticking to the original approach and meeting the users and developers needs.

Should we revise the original approach?

@pharmaverse/admiral-devs , what do you think?

**Comment by bms63** [comment]
Maybe this should be a pre-read for tomorrow's admiral sponsors and leads meetings?  @MichaelRimler @rossfarrugia @koegerr @lucyhoch @upadhyor @duniek @statasaurus

**Comment by upadhyor** [comment]
Looking forward to discuss this tomorrow.  Hopefully, we can find the right balance.

**Comment by rossfarrugia** [comment]
OK here's my attempt to summarise a lengthy and really good discussion between the sponsors and leads on this topic....

overall the wish is to stay with the programming strategy of keeping functions fairly lean because of the added transparency and simplicity for usage. we don't want to make admiral a black-box or a collection of super generic and complex functions that cover a million different needs. BUT everyone agreed this does have to balance out with the needs of the users. so flexibility/arguments can be added where absolutely needed if MANY companies (including Roche & GSK) have that analysis need. the admiral leads would have to be the gatekeepers here when needed for contentious decisions to ensure the balance stays appropriate and in line with other priorities on our roadmap - it's OK to say no to user requests if we have clear rationale

which brings us to... the main gap we all recognised is that nowhere in our documentation does it really explain clearly this strategy and the WHY behind our design decisions, and it came up a lot in the external testing feedback. so we need to add this to the README and Get Started first site page as essential reading for new users. this could be combined with details on how we expect companies to adopt admiral (i.e. admiral core will never cover 100%, so in what scenarios should you expect to need to use admiral.company level)

happy to assign myself and take a stab at the wording of this section, but i'll definitely appreciate a review from the leads and dev team as it's something that's way easier to talk through and present, rather than putting down in site text.

let me know what i missed guys! i could only scribble notes down so fast...

**Comment by thomas-neitmann** [comment]
Please take a look at #868 @rossfarrugia. Thanks!

**Comment by bundfussr** [comment]
@rossfarrugia , all the points in your comment and in the README make sense.

However, I think we need a more detailed guidance, especially regarding flexibility and nesting. For example  in the last release we deprecated `derive_var_basec()` and questioned functions like `derive_var_ady()`, `derive_var_astdy()`, `derive_var_trtsdtm()`. Is this the right direction?
Or in the proposed TRTEMFL derivation in https://github.com/pharmaverse/admiral/pull/842/files there is plain R code for "Get the last value before TRTSDTM" and "Get the worst value after or at TRTSDTM". Should this be kept or be replaced by a call of the admiral function `filter_extreme()`?

**Comment by rossfarrugia** [comment]
@bundfussr - good question. i'd assume we could put something in our programming strategy vignette to cover this? as it's most relevant for developers/contributors. i'm honestly not sure if we'd ever be able to spell out all rules that cover every case though, so the tech leads of admiral would always be the gate-keepers for any contentious decisions. sometimes there won't be a perfect answer either way and we just have to go with what we think best, as long as we have the admiral philosophies in the back of our mind. 
e.g. for your TRTEMFL example we know we will always need to re-use some pieces, just like we do with computations and developer utilities like the assertions, but maybe the guidance would say something like be mindful of nesting becoming too deep (e.g. we don't want for a user or say FDA reviewer to find out what one admiral function does they'd have to open another function which then leads them to another function and so on...). it's akin to when you're trying to understand a complex topic via a Wikipedia page and as you start to read it you find a word you don't understand that takes you to a new page, and so on... you end up on some tangential journey and forget what you were looking for in the first place :) 

@bms63 @thomas-neitmann - these are my 2 cents but i'm way overstepping here as sponsor, so this would be a call i'd trust you guys to know the best suggestion for.

**Comment by bundfussr** [comment]
@rossfarrugia , I agree that it is challenging to spell out rules. However, I hope we can find some rules which reduce the number of request raised by contributors and extension package developers and reduce the work-load for the tech leads. (see https://github.com/pharmaverse/admiral/issues/954).

In your example you mentioned an interesting point. Do you expect that users and FDA reviewers read the _code_ of admiral functions?

I assumed that the code is relevant for developers only. I would expect that users and FDA reviewers read the _documentation_ of the function when they want to find out how a function works.

I think the documentation should provide a high-level purpose of the function and a detailed description which allows to determine the output of the function depending on the input without knowing the code of the function. If the developer has issues to provide such documentation, I would consider this as a strong indication that there is something wrong with the design of the function.

**Comment by rossfarrugia** [comment]
@bundfussr yes users and FDA will at times read the code. FDA even request readable code as part of submissions for key endpoints. in our Roche SAS-based solution i would argue that if users were able to read and understand more of the code then they'd be far more equipped to solve their own questions. 10 years on and we're still getting countless questions and plus we use 25+ superusers. transparency really is key! at Roche at least we don't want people that know how to click a button and check a log, they should understand the code enough to be able to consider whether it fits the purposes of their protocol and study input data. in many cases the documentation alone is enough here as you say, but when they need to dig deeper for less standard usages they should be able to. 

thanks for creating the new issue! sounds a good plan that you have outlined.

**Comment by bundfussr** [comment]
@rossfarrugia , I am quite surprised by the requirement because it questions almost all admiral functions. In most functions a major part of the code does not process the input dataset but does other things like checking, quoting and unquoting of parameters, determining how the input should be processed (e.g., does the input need to be filtered or sorted). To fulfill the requirement we would need to remove all this code doing other things such that the code consist only of plain R function calls processing the input dataset without any conditional processing. This would result in thousands of functions in admiral and the extension packages. Of course, these could not be implemented explicitly. So we would need a sort of code generator. But this would be a completely different tool!??

This requirement could be one of the root causes for the pain points.

Are there any other requirements we have not considered so far?

**Comment by rossfarrugia** [comment]
I guess it comes down to how you define readable @bundfussr - for me developer assertions etc are of course fine and needed to make the functions robust, but the actual piece of the code that performs the derivation should be easy to get to and understand. this is in the programming strategy: https://pharmaverse.github.io/admiral/articles/programming_strategy.html. let's discuss more at the call you set-up, no need to rush into any changes.

**Comment by koegerr** [comment]
I agree with Ross. Readable code opens up a lot of interpretation. I think key is that somebody can go into a function and the code in there is described. But I also find it difficult to clearly define what readable means. 
The FDA basically wants to be able to grasp how an algorithm works. Given our detailed documentation of each function this is doable for all admiral functions (or at least most of them).

https://github.com/pharmaverse/admiral/blob/main/R/derive_var_ady.R this is readable code for me, it has all elements to understand how the ady is calculated. 


I.e #841 creating adae variables for astdtm and trtemfl is probably not readable since it is not a lean function and not readable imo.
