### ISSUE TITLE
Establish a periodic release schedule

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#881]
Hi all,

Is there any thoughts, or previous discussion, on establishing a release schedule?

For example, every two months releasing a new version of admiral onto CRAN.  This would give us roughly 4 2-week sprint cycles to make updates.  It doesn't have to be locked in tight, as we might want to deploy a new version at the start of a conference, talk, etc,.

I think this would help us sustain momentum and prioritize tasks as we are always working towards a release date.  It also gives users the knowledge that an update, bug fix they requested could be implemented in a timely manner.  As well as keeping the release checks in the front of our minds!  Plus, the many admiralxyz spin-off packages could also benefit from knowledge that an issue facing the base package would be fixed in the next release (or at least be prioritized to be fixed by next release).

Thoughts?  Sorry if this has been discussed before!

@pharmaverse/admiral-devs
@pharmaverse/admiral

**Comment by thomas-neitmann** [comment]
Is there value of sticking to a fixed schedule? Ifeel like we should rather aim for certain functionality to be included in a release and only release once this has been implemented. Also, if we find bugs I'd really like to quickly fix those and submit a "hot fix" release.

**Comment by bundfussr** [comment]
I agree that we should fix bugs quickly. What about checking in the Thursday stand up if there are any bug fixes and in the affirmative release them on Friday?

At the moment I see not much benefit of a fixed schedule for feature releases because we are still in the experimental phase. However, once admiral is used by study teams it could become important. I think if a study team wants to implement a derivation, it is crucial that the implementation is available at the time of the reporting event. So having a fixed release cycle could it make easier for study teams to contribute to admiral.

It may also be helpful when developing TA or company specific packages.

**Comment by bms63** [comment]
Okay, fixing number of issues makes sense as a guide-star.  As well as it being still in the experimental phase.

I wouldn't think having a fixed schedule would prevent things like hot-fixes.  Also, two months was just an example.  We can move the schedule around.  Just publicly stating "Stay tuned for a mid-April release" for xyz enhancements could give us a little more emphasis on the work and ask for additional resources if we are running behind schedule.  

Also,  just musing on if `admiralhiv `was waiting on several non-hot-fix issues to be implemented, then they could plan their release knowing when we are releasing as we have a "fixed/proposed" schedule.  This goes for the admiralonc, xportr, adimiralgsk, admiralroche, metacore, metatools. For now, we don't really have this dependency/waiting problem cause all the packages are experimental and nothing is really in production for study teams.  

I'll keep this issue up for another day or so to see if anyone else has comments they would like to add.  Thanks for the discussion!

**Comment by duniek** [comment]
I'd like to add some historical context :o)
The first few releases were quite regular (every 2 months), although this was by chance. We were mostly driven by external context (e.g. internal user testing, industry testing etc.). I agree that we should be pragmatic (flexible) and just communicate with users and across dev teams well, rather than fix ourselves within a regular time-frame. On the other hand, my guess is that we will probably again become more regular even if we don't plan for it.
Eventually, like Stefan pointed out, study teams will need to have more predictability, so stabilizing into bi-monthly releases will potentially become a user requirement. This could be expected at Roche in about 12 months time.
