### ISSUE TITLE
Update derive_var_disposition_status.R to have more meaningful argument

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiral#911]
Currently the argument uses x - but I think it should have a more meaningful name 

![image](https://user-images.githubusercontent.com/10111024/153418572-f8e1045a-5c8a-4478-bf6e-dfca379700bd.png)

**Comment by teckla-gsk** [comment]
@bms63 what name would you suggested other than 'x' , maybe 'disposition_var' since a disposition variable is expected for that format function. That said, is this still necessary? It looks like the function `derive_var_disposition_status`  which uses this format utility is depreciated as of last month. @amsmith214
