### ISSUE TITLE
Documentation:  Update documentation of derive_var_trtredtm

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiral#936]
### Please select a category the issue is focused on?

Function documentation

### Let us know where something needs a refresh or put your idea here!

Update details section of `derive_var_trtedtm()`. It should also mention the imputation done internally.

**Comment by rossfarrugia** [comment]
@bundfussr @thomas-neitmann - bit confused with this one whether the PR #938 was only for the onboarding session or the whole issue was too? it probably puts people off picking this issue up if they see a PR already attached. if it was just a test then recommend to close. otherwise, if needed add more details and maybe add the good first issue label

**Comment by bundfussr** [comment]
I think the PR is not related to the issue.

However, I would not add the good first issue label because the function has the questioning label.

Should we decide before the next release if we deprecate the functions with the questioning label? @rossfarrugia , @thomas-neitmann , @bms63 , @koegerr , what do you think?

**Comment by rossfarrugia** [comment]
agree @bundfussr - issue created to help push along a decision on these questioning functions for the next release.
